const Words: { [key: string]: string } = {
    'Dada dadda?': 'Want to buy a lamp?',
    'Bub?': 'Used when one does not understand',
    Dubababa: 'Many(very)',
    Dadda: 'Lamp',
    Dubba: 'Friends',
    Duba: 'You',
    Duda: 'Me',
    Bubu: 'Dudbear',
    Gugu: 'Any other species',
    Baba: 'Music',
    Dada: 'Please',
    Gak: 'Used to show displeasure',
    Dub: 'Yes(greetings)',
    Dud: 'No(goodbye)',
    Du: 'Little',
    Da: 'Light(stars)',
    Ba: 'Night',

    'んぐんま　ぐまー　ま？': 'ランプはいかが？',
    'んぐんま ぐまー ま？': 'ランプはいかが？',
    ぐままままー: 'たくさん',
    ぐまぐまま: '友達',
    ぐまぐま: 'アナグマ',
    まぐまぐ: 'アナグマ以外の生き物',
    んぐんま: 'ランプ',
    ぐーまー: '音楽',
    ぐまー: 'どうぞ',
    'ぐま！': 'あいさつ(YES)',
    まっ: 'さようなら(NO、ダメ)',
    'ぐ～': 'あなた',
    'ぐ〜': 'あなた',
    'ま～': '私',
    'ま〜': '私',
    んぐ: '光(星)',
    んま: '闇(夜)',
    ぐげ: '嫌な気持ちの表現',
    'ま？': '？',
    ぐ: '少し',
};

export default Words;
