export const PabpabWords: { [key: string]: string } = {
    pukapuka: 'slowly(relaxed, "What will be, will be")',
    purechi: 'friend',
    saldine: 'island(Saldine Island)',
    pabpab: 'us',
    paketo: 'but(still)',
    rikuku: 'medicine',
    sanami: 'south',
    tatoru: 'dance',
    kairu: 'guide(teach)',
    michu: 'secret',
    nosta: 'north',
    santo: 'thanks',
    sonna: 'sorry',
    treja: 'treasure',
    ueshi: 'west',
    taan: 'time',
    kain: 'tell(teach)',
    ishi: 'east',
    kohl: 'go',
    poto: 'more(amazing)',
    temi: 'enemy(bad person)',
    ain: 'during(a period)',
    koh: 'here(this)',
    nah: 'fish',
    ko: 'here(this)',
    ni: 'you(that)',
    no: 'wrong(bad)',
    roi: 'rock(stone)',

    パブパブ: '私達',
    プカプカ: 'のんびり(ゆっくり/なるようになる)',
    トレジャ: '宝物',
    アイン: '～の間',
    ウェシ: '西',
    カイル: '案内(教え)',
    サナミ: '南',
    サント: '有難う',
    ソンナ: 'ごめんなさい',
    タアン: '時間',
    タトル: '踊る',
    ノスタ: '北',
    パケト: 'けれども',
    プレチ: '友達(いいやつ)',
    ミチュ: '秘密',
    リクク: '薬',
    テミ: '悪いやつ',
    イシ: '東',
    ボト: 'もっと(すごい)',
    ロイ: '石(岩)',
    ナー: '魚',
    コ: 'ここ(これ)',
    ニ: 'あなた(それ)',
    ノ: '違う(ダメ)',
};
